# my global config
 global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

 scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
     - targets: ['10.0.5.93:9090']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:9089']

  - job_name: 'config-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8091']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8092']

  - job_name: 'downstream-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8095']

  - job_name: 'upstream-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8094']

  - job_name: 'rsvp'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8097']

  - job_name: 'ticket'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8091']

  - job_name: 'search'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8093']

  - job_name: 'user-registration'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8090']

  - job_name: 'show-scheduler'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8099']

  - job_name: 'recommendation'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:8098']

  - job_name: 'email'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:9000']

  - job_name: 'ticket-engine'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
     - targets: ['10.0.5.93:9001']

