#spring:
# logging:
#  file: logs/dev_app.log
#  pattern:
#   console: "%d %-5level %logger : %msg%n"
#   file: "%d %-5level [%thread] %logger : %msg%n"
#  level:
#   org.springframework.web: DEBUG
#   com.stackroute.controllers: DEBUG
#   org.hibernate: DEBUG
#
# data:
#  mongodb:
#   authentication-database: admin
#   username: root123 
#   password: root123
#   database: movie
#   port: 27017 
#   host: localhost     
#       
#
# cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: 172.23.238.198:9092
#      bindings:
#        movie-event-in:
#          destination: MovieEvent
#          contentType: application/json
#        movie-in:
#          destination: Movie
#          contentType: application/json
#        ticketed-event-in:
#          destination: TicketedEvent
#          contentType: application/json
###### data: 
######  mongodb:
######   port: 27017
######   host: localhost
######   database: test
######   uri: mongodb://172.23.238.255:27017/user_movie
####
###### 
#####
#####server:
##### port: 8093
####
###### data:
######      mongodb:
######         uri: mongodb://172.23.238.255:27000/test
#####
#####server:
##### port: 8093
##### 
###
