#
#logging:
# file: logs/dev_app.log
# pattern:
#   console: "%d %-5level %logger : %msg%n"
#   file: "%d %-5level [%thread] %logger : %msg%n"
# level:
#   org.springframework.web: DEBUG
#   com.stackroute.movieapp.controller: DEBUG
#   org.hibernate: DEBUG
#   
#   
#spring:
#  data:
#      mongodb:
#         uri: mongodb://0.0.0.0:27000/test
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#      bindings:
#        updated-movie-event-in:
#          destination: UpdatedShowEvent
#          contentType: application/json         
#        movie-event-in:
#          destination: MovieEvent
#          contentType: application/json
#        show-in:
#          destination: Show
#          contentType: application/json
#        ticketed-event-in:
#          destination: TicketedEvent
#          contentType: application/json
#        movie-in:
#          destination: Movie
#          contentType: application/json
#        theatre-in:
#          destination: Theatre
#          contentType: application/json
#        updated-movie-event-out:
#          destination: UpdatedMovieEvent
#          contentType: application/json    
#        movie-event-out:
#          destination: MovieEvent
#          contentType: application/json
#        ticketed-event-out:
#          destination: TicketedEvent
#          contentType: application/json
#        movie-out:
#          destination: Movie
#          contentType: application/json
#        theatre-out:
#          destination: Theatre
#          contentType: application/json